# Build customization
builds:
  - id: main
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
    gomips:
      - softfloat
release:
  github:
    owner: utilitywarehouse
    name: wiresteward
archives:
  - builds:
      - main
    format: binary
    files:
      - none*
